# Change these first
owner: mintvn # Your GitHub organization or username, where this repository lives
repo: mintvn-status-test # The name of this repository

sites:
  - name: Mint Vietnam
    url: https://mintvietnam.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.mintvietnam.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Mintvn Status
  introTitle: "**Mintvn Status**"
  introMessage: This is the system status for the Mint Vietnam service.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
